# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-11 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=300)),
                ('price', models.FloatField(default=0.0)),
            ],
        ),
    ]
