# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 04:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splogs', '0002_auto_20160811_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pmt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2016, 8, 25))),
                ('name', models.CharField(max_length=100)),
                ('amount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateField(default=datetime.date(2016, 8, 25)),
        ),
    ]
