# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splogs', '0003_auto_20160825_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pmt',
            old_name='name',
            new_name='fromN',
        ),
        migrations.AddField(
            model_name='pmt',
            name='toN',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
