# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-16 20:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splogs', '0004_auto_20160825_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='logs',
            name='date',
            field=models.DateField(default=datetime.date(2016, 9, 16)),
        ),
        migrations.AlterField(
            model_name='pmt',
            name='date',
            field=models.DateField(default=datetime.date(2016, 9, 16)),
        ),
    ]
